apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: ds-busybox1
spec:
  selector:
    matchLabels:
      name: ds-busybox
  template:
    metadata:
      labels:
        name: ds-busybox
    spec:
      containers:
      - name: busybox
        image: busybox
        args:
        - sleep
        - "3600"

