apiVersion: v1
kind: ReplicationController
metadata:
  name: basic-pod1-rc
spec:
  replicas: 3
  selector:
    app: basic-pod1-app
  template:
    metadata:
      labels:
        app: basic-pod1-app
    spec:
      containers:
      - name: busybox-container
        image: busybox
        args:
        - sleep
        - "3600"

