apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web2
spec:
  serviceName: "busybox"
  replicas: 1
  selector:
    matchLabels:
      app: busybox
  template:
    metadata:
      labels:
        app: busybox
    spec:
      containers:
      - name: busybox
        image: busybox
        args:
        - sleep
        - "3600"

